/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminDevisRouteImport } from './routes/admin.devis'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRecrutementRouteImport } from './routes/admin.recrutement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/admin/devis',
  path: '/admin/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecrutementRoute = AdminRecrutementRouteImport.update({
  id: '/admin/recrutement',
  path: '/admin/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recrutement': typeof AdminRecrutementRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recrutement': typeof AdminRecrutementRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recrutement': typeof AdminRecrutementRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/devis'
    | '/realisations'
    | '/recrutement'
    | '/admin/contacts'
    | '/admin/devis'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/recrutement'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/devis'
    | '/realisations'
    | '/recrutement'
    | '/admin/contacts'
    | '/admin/devis'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/recrutement'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/devis'
    | '/realisations'
    | '/recrutement'
    | '/admin/contacts'
    | '/admin/devis'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/recrutement'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  RealisationsRoute: typeof RealisationsRoute
  RecrutementRoute: typeof RecrutementRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDevisRoute: typeof AdminDevisRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRecrutementRoute: typeof AdminRecrutementRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/admin/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recrutement': {
      id: '/admin/recrutement'
      path: '/admin/recrutement'
      fullPath: '/admin/recrutement'
      preLoaderRoute: typeof AdminRecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  RealisationsRoute: RealisationsRoute,
  RecrutementRoute: RecrutementRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDevisRoute: AdminDevisRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRecrutementRoute: AdminRecrutementRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
